
package testws1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestService1Service", targetNamespace = "http://testws1/", wsdlLocation = "http://localhost:8765/DateReverse?wsdl")
public class TestService1Service
    extends Service
{

    private final static URL TESTSERVICE1SERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTSERVICE1SERVICE_EXCEPTION;
    private final static QName TESTSERVICE1SERVICE_QNAME = new QName("http://testws1/", "TestService1Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8765/DateReverse?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTSERVICE1SERVICE_WSDL_LOCATION = url;
        TESTSERVICE1SERVICE_EXCEPTION = e;
    }

    public TestService1Service() {
        super(__getWsdlLocation(), TESTSERVICE1SERVICE_QNAME);
    }

    public TestService1Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTSERVICE1SERVICE_QNAME, features);
    }

    public TestService1Service(URL wsdlLocation) {
        super(wsdlLocation, TESTSERVICE1SERVICE_QNAME);
    }

    public TestService1Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTSERVICE1SERVICE_QNAME, features);
    }

    public TestService1Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestService1Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestService1
     */
    @WebEndpoint(name = "TestService1Port")
    public TestService1 getTestService1Port() {
        return super.getPort(new QName("http://testws1/", "TestService1Port"), TestService1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestService1
     */
    @WebEndpoint(name = "TestService1Port")
    public TestService1 getTestService1Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://testws1/", "TestService1Port"), TestService1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTSERVICE1SERVICE_EXCEPTION!= null) {
            throw TESTSERVICE1SERVICE_EXCEPTION;
        }
        return TESTSERVICE1SERVICE_WSDL_LOCATION;
    }

}
