
package testws1;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestService1", targetNamespace = "http://testws1/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestService1 {


    /**
     * 
     * @param size
     * @param name
     * @param floor
     * @param buildingId
     */
    @WebMethod
    @Action(input = "http://testws1/TestService1/addRoomRequest", output = "http://testws1/TestService1/addRoomResponse")
    public void addRoom(
        @WebParam(name = "buildingId", partName = "buildingId")
        int buildingId,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "floor", partName = "floor")
        String floor,
        @WebParam(name = "size", partName = "size")
        int size);

    /**
     * @param roomName
     * @param buildingId
     * @return
     */
    @WebMethod
    @Action(input = "http://testws1/TestService1/searchRoomRequest", output = "http://testws1/TestService1/searchRoomResponse")
    public Room searchRoom(
        @WebParam(name = "buildingId", partName = "buildingId")
        int buildingId,
        @WebParam(name = "roomName", partName = "roomName")
        String roomName);

    /**
     * @param buildingId
     * @return returns testws1.RoomArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://testws1/TestService1/getRoomsRequest", output = "http://testws1/TestService1/getRoomsResponse")
    public Room[] getRooms(
        @WebParam(name = "buildingId", partName = "buildingId")
        int buildingId);

    /**
     * 
     * @param size
     * @param roomName
     * @param buildingId
     */
    @WebMethod
    @Action(input = "http://testws1/TestService1/changeSizeRequest", output = "http://testws1/TestService1/changeSizeResponse")
    public void changeSize(
        @WebParam(name = "buildingId", partName = "buildingId")
        int buildingId,
        @WebParam(name = "roomName", partName = "roomName")
        String roomName,
        @WebParam(name = "size", partName = "size")
        int size);

}
